---
title: Data Mining en Ciencia y Técnica - TP1
author: Ariel Aguirre, Miguel Barros, José Badillo, Diego Dell'Era
output: pdf_document
---

TP1 - parte 2
=============


```{r, echo=FALSE}
# cargamos el dataset.
glx <- read.csv("dmcyt_tp2.csv", header = T, stringsAsFactors = F, sep = '|')
glx$mc_class <- as.factor(glx$mc_class)

# viene con bocha de decimales; evitemos que R los trunque
options(digits=16)
```

Quitamos outliers:

```{r, results='markup', warning=FALSE, message=FALSE}
glx_sin_outliers <- subset(glx, apd_rmag > -3.2)
glx_sin_outliers <- subset(glx_sin_outliers, bjmag < -7.0)
glx_sin_outliers <- subset(glx_sin_outliers, ujmag < -10.0)
glx_sin_outliers <- subset(glx_sin_outliers, vjmag < -10.0)
glx_sin_outliers <- subset(glx_sin_outliers, usmag < -10.0)
glx_sin_outliers <- subset(glx_sin_outliers, gsmag < -9.0)
glx_sin_outliers <- subset(glx_sin_outliers, rsmag < -9.0)
# glx_sin_outliers <- subset(glx_sin_outliers, bbmag < -9.0) # todos los valores en 0?
# glx_sin_outliers <- subset(glx_sin_outliers, ubmag < -10.0) # todos los valores en 0?
# glx_sin_outliers <- subset(glx_sin_outliers, vbmag < -10.0) # todos los valores en 0? (antes era vnmag)

nrow(glx) - nrow(glx_sin_outliers)
```

Buscamos datos faltantes:

```{r, results='markup', warning=FALSE, message=FALSE}
apply(glx_sin_outliers, 2, function(x) anyNA(x))
glx_sin_faltantes <- glx_sin_outliers[complete.cases(glx_sin_outliers),]
nrow(glx_sin_outliers) - nrow(glx_sin_faltantes)
```

```{r, echo=FALSE}
# Guardamos el dataset. Sólo van con comillas la clase ('mc_class') y el signo de la declinación ('de_'); el resto son números
# write.table(format(glx_sin_faltantes, digits=16), file = "dmcyt_tp2.tarea_1.csv", row.names = FALSE, na="", col.names = TRUE, sep="|", quote = c(5, 15))
```

